version: "3.8"
services:
  tweb.dependencies:
    container_name: tweb.dependencies
    build:
      context: .
      dockerfile: .docker/Dockerfile_dependencies
    volumes:
      - "./node_modules:/app/node_modules"
    command: pnpm install

  tweb.develop:
    container_name: tweb.develop
    build:
      context: .
      dockerfile: .docker/Dockerfile_develop
    volumes:
      - "./:/app"
    ports:
      - 8080:8080
    command: pnpm start-in-docker

  tweb.production:
    container_name: tweb.production
    build:
      context: .
      dockerfile: .docker/Dockerfile_production
    ports:
      - 80:80
